In [ ]:
import pandas as pd
import csv


csv_path = r"C:\Users\nikla\Desktop\github_projects\CatBondPricing_EVT\data\earthquakes_us_1950-1987.feather"
out_path = r"CatBondPricing_EVT\data"

raw_data = pd.read_feather(csv_path) 
raw_data

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,1950-01-03T11:26:30.040Z,33.940667,-115.888167,6.000,3.37,ml,6.0,308.0,1.00200,0.470,...,2016-01-28T18:16:41.860Z,"28km SE of Twentynine Palms, CA",earthquake,2.23,31.61,0.194,12.0,reviewed,ci,ci
1,1950-01-05T13:45:48.730Z,33.574833,-119.321500,6.000,3.11,ml,7.0,245.0,0.92350,0.560,...,2016-01-28T18:12:01.550Z,"27km WNW of Santa Barbara Is., CA",earthquake,2.62,31.61,0.080,13.0,reviewed,ci,ci
2,1950-01-07T09:37:33.670Z,31.983500,-116.819167,6.000,4.07,ml,5.0,334.0,0.95140,0.460,...,2016-01-28T17:53:48.210Z,"16km NW of El Sauzal, B.C., MX",earthquake,6.45,31.61,0.139,13.0,reviewed,ci,ci
3,1950-01-09T13:24:56.940Z,34.066167,-116.959000,0.040,3.78,ml,7.0,227.0,0.30750,0.270,...,2016-01-28T17:58:09.940Z,"9km ENE of Yucaipa, CA",earthquake,1.21,1.40,0.110,14.0,reviewed,ci,ci
4,1950-01-09T21:40:35.740Z,33.752333,-116.018667,6.000,3.08,ml,5.0,305.0,0.80920,0.590,...,2016-01-28T17:58:10.620Z,"16km ENE of Coachella, CA",earthquake,4.34,31.61,0.106,6.0,reviewed,ci,ci
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,1987-09-15T10:48:37.350Z,36.281833,-120.402667,9.403,3.26,md,48.0,64.0,0.05856,0.070,...,2016-12-07T10:55:00.730Z,"16 km NNW of Coalinga, California",earthquake,0.13,0.27,0.120,110.0,reviewed,nc,nc
19996,1987-09-16T00:07:34.340Z,40.322833,-124.621333,19.615,3.40,ml,46.0,232.0,0.26580,0.070,...,2016-12-07T10:56:51.660Z,"41 km SW of Ferndale, California",earthquake,0.41,0.54,NaN,4.0,reviewed,nc,nc
19997,1987-09-16T13:22:00.120Z,31.651000,-115.795000,5.842,3.11,mc,0.0,315.7,NaN,0.292,...,2016-02-03T22:18:04.260Z,"73km E of Maneadero, B.C., MX",earthquake,NaN,NaN,NaN,9.0,reviewed,ci,ci
19998,1987-09-16T20:10:42.200Z,49.083000,-122.709000,1.000,3.00,ml,NaN,NaN,NaN,NaN,...,2016-07-24T20:20:15.900Z,"4 km WSW of Langley, Canada",earthquake,NaN,NaN,NaN,NaN,reviewed,pgc,us
19999,1987-09-17T08:31:26.630Z,41.186500,-113.141000,13.670,3.67,ml,24.0,253.0,0.56470,0.220,...,2018-08-28T03:33:39.160Z,"85 km W of Hooper, Utah",earthquake,2.52,0.92,NaN,2.0,reviewed,uu,uu

In [5]:
data = raw_data
data = data[data["place"].str.endswith((", CA", ", California"), na=False)]
data = data.reset_index(drop=True)
data["time"] = pd.to_datetime(data["time"])

data = data.drop(columns=
                     ["type", "status", "updated", "magNst", 
                      "locationSource", "magSource", "depthError", 
                      "horizontalError", "nst", "gap", "place"]

                     )

data

,time,latitude,longitude,depth,mag,magType,dmin,rms,net,id,magError
0,1950-01-03 11:26:30.040000+00:00,33.940667,-115.888167,6.000,3.37,ml,1.00200,0.47,ci,ci3361691,0.194
1,1950-01-05 13:45:48.730000+00:00,33.574833,-119.321500,6.000,3.11,ml,0.92350,0.56,ci,ci3361753,0.080
2,1950-01-09 13:24:56.940000+00:00,34.066167,-116.959000,0.040,3.78,ml,0.30750,0.27,ci,ci3361958,0.110
3,1950-01-09 21:40:35.740000+00:00,33.752333,-116.018667,6.000,3.08,ml,0.80920,0.59,ci,ci3361971,0.106
4,1950-01-11 21:41:34.340000+00:00,33.945667,-118.179833,3.440,3.89,ml,0.20240,0.43,ci,ci3362017,0.103
...,...,...,...,...,...,...,...,...,...,...,...
13524,1987-09-13 04:14:18.360000+00:00,39.784333,-121.868667,24.069,3.27,md,0.12160,0.13,nc,nc105697,0.210
13525,1987-09-14 07:25:43.920000+00:00,39.473000,-122.909667,-1.157,3.00,ml,0.02793,0.39,nc,nc105753,NaN
13526,1987-09-15 02:06:42.730000+00:00,36.118000,-119.991333,24.016,3.40,ml,0.11170,0.21,nc,nc10084691,NaN
13527,1987-09-15 10:48:37.350000+00:00,36.281833,-120.402667,9.403,3.26,md,0.05856,0.07,nc,nc105842,0.120
13528,1987-09-16 00:07:34.340000+00:00,40.322833,-124.621333,19.615,3.40,ml,0.26580,0.07,nc,nc10085040,NaN

In [6]:
data["mag"].describe()

for u in [4.0, 4.5, 5.0, 5.5, 6.0]:
    n = (data["mag"] >= u).sum()
    print(f"M >= {u}: {n}")

M >= 4.0: 1501
M >= 4.5: 510
M >= 5.0: 155
M >= 5.5: 47
M >= 6.0: 10